# Site settings
title: Zachary Herbert
email: zach@dogefriendly.net
description: "Portfolio Website for Zachary Herbert."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00A0B0 #80B3FF
  secondary: 556270 #FD6E8A
  secondary-dark: 3F4954 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:


# Postal address (add as many lines as necessary)
address:
  - line: zach@dogefriendly.net

# Build settings
markdown: kramdown
permalink: pretty
